### ISSUE TITLE
configure fails determining libboost-thread version

### ISSUE THREAD

**Issue by lbergesio** [IRATI/traffic-generator#16]
checking whether debug related features have been enabled... no
checking for boostlib >= 1.55... yes
checking whether the Boost::Thread library is available... yes
configure: error: Could not find a version of the library!

You have to execute it with --with-boost-libdir=/usr/lib/i386-linux-gnu/ in order to succeed

**Comment by msune** [comment]
How were these boost libs installed? This is not the default installation path afaik...

**Comment by lbergesio** [comment]
apt-get install libboost-all-dev in ubuntu

**Comment by edugrasa** [comment]
Same thing in Debian

**Comment by msune** [comment]
But are you running a 32 bit distro?? The right path should be:

/usr/lib/x86_64-linux-gnu/

Btw, ehese checks are pretty old AFAIS (AX_BOOST):

https://github.com/IRATI/traffic-generator/tree/master/m4

We should probably use:

https://github.com/tsuna/boost.m4

**Comment by lbergesio** [comment]
64 bits: root@irati-vm:/usr/local/irati/bin# uname -a
Linux irati-vm 3.15.0 #24 SMP Thu Aug 6 10:10:03 CEST 2015 x86_64 GNU/Linux

**Comment by msune** [comment]
@dstaesse I just checked with Leo. His problem and Edu's one is that the boost that they have comes from the IRATI development VM, which was installed by hand (debian 7 boost packages are 1.46). That's why the macros were not finding the libs.

On the other side, the upgrade to boost.m4 is better, to be able to support newer boost libraries and compilers. I will check your problem.

Can you specify please which OS version and arch are you using, and which packages were you installing?

**Comment by dstaesse** [comment]
@msune: running Debian 7.1 amd64.
I installed libboost155-all-dev

```
dstaesse@m:~$ dpkg --get-selections | grep libboost
libboost-atomic1.55-dev:amd64                   install
libboost-atomic1.55.0:amd64                     install
libboost-chrono1.55-dev:amd64                   install
libboost-chrono1.55.0:amd64                     install
libboost-context1.55-dev:amd64                  install
libboost-context1.55.0:amd64                    install
libboost-coroutine1.55-dev:amd64                install
libboost-date-time1.55-dev:amd64                install
libboost-date-time1.55.0:amd64                  install
libboost-exception1.55-dev:amd64                install
libboost-filesystem1.55-dev:amd64               install
libboost-filesystem1.55.0:amd64                 install
libboost-graph-parallel1.55-dev                 install
libboost-graph-parallel1.55.0                   install
libboost-graph1.55-dev:amd64                    install
libboost-graph1.55.0:amd64                      install
libboost-iostreams1.55-dev:amd64                install
libboost-iostreams1.55.0:amd64                  install
libboost-locale1.55-dev:amd64                   install
libboost-locale1.55.0:amd64                     install
libboost-log1.55-dev                            install
libboost-log1.55.0                              install
libboost-math1.55-dev:amd64                     install
libboost-math1.55.0:amd64                       install
libboost-mpi-python1.55-dev                     install
libboost-mpi-python1.55.0                       install
libboost-mpi1.55-dev                            install
libboost-mpi1.55.0                              install
libboost-program-options1.55-dev:amd64          install
libboost-program-options1.55.0:amd64            install
libboost-python1.55-dev                         install
libboost-python1.55.0                           install
libboost-random1.55-dev:amd64                   install
libboost-random1.55.0:amd64                     install
libboost-regex1.55-dev:amd64                    install
libboost-regex1.55.0:amd64                      install
libboost-serialization1.55-dev:amd64            install
libboost-serialization1.55.0:amd64              install
libboost-signals1.55-dev:amd64                  install
libboost-signals1.55.0:amd64                    install
libboost-system1.55-dev:amd64                   install
libboost-system1.55.0:amd64                     install
libboost-test1.55-dev:amd64                     install
libboost-test1.55.0:amd64                       install
libboost-thread1.55-dev:amd64                   install
libboost-thread1.55.0:amd64                     install
libboost-timer1.55-dev:amd64                    install
libboost-timer1.55.0:amd64                      install
libboost-wave1.55-dev:amd64                     install
libboost-wave1.55.0:amd64                       install
libboost1.55-all-dev                            install
libboost1.55-dev:amd64                          install
libboost1.55-tools-dev                          install
```

**Comment by msune** [comment]
Where did you get these pacakges? Debian 7 (wheezy) libboost are 1.49:

https://packages.debian.org/wheezy/libboost-all-dev (meta-package)

So they must come from another repo other than the std.

**Comment by dstaesse** [comment]
sources.list is set to jessie main

**Comment by sandervrijders** [comment]
Also had the error

```
checking whether the Boost::Thread library is available... yes
configure: error: Could not find a version of the library!
```

Solved it by installing libboost-all-dev. Seems the build system indeed doesn't generate the correct error.

**Comment by msune** [comment]
The error is correct. There was a boost library in the system, but too old (required >= 1.55)

**Comment by sandervrijders** [comment]
Ah, ok, so it's "Could not find a correct version of the library". Obscure error message imho.

**Comment by msune** [comment]
That is a message from `boost.m4`, you can add an issue there:

https://github.com/tsuna/boost.m4

**Comment by sandervrijders** [comment]
But is that already merged in? isn't it an error of the older m4 files?

**Comment by msune** [comment]
No it is not.. were you reporting over the original codebase? 

Please specify that you are doing so if you are commenting _after_ a fix (PR) is issued, otherwise it confuses everyone.

**Comment by sandervrijders** [comment]
Yeah I was, else I would have commented on the PR. But ok, will make it more clear in the future.
