### ISSUE TITLE
Install Rina-Tgen (Error)

### ISSUE THREAD

**Issue by DjalmaFilho-UFPE** [IRATI/traffic-generator#23]
Hello,

I am trying to install rina-TGen, but presents the following information;

checking for LIBRINA in ...
configure: error: Your system lacks of support librina

I am using the 4.1.16 stack IRATI prototype.

You can help me install librina.

Thank you very much in advance.

Problem solved!

**Comment by dstaesse** [comment]
Good to see you got things sorted out. Have fun with RINA...
